### PR TITLE
Fix `AsyncSeek` of `TokioCompatFile`

### LINKED ISSUE #80: Incorrect behavior about `AsyncSeek` of `TokioCompatFile`
Sometimes `AsyncSeek` to `TokioCompatFile` will set the offset to the wrong place. This error occurs in https://github.com/apache/incubator-opendal/pull/2263 https://github.com/apache/incubator-opendal/actions/runs/4976970726/jobs/8905529556

I guess the problem is about https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L354

https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L383-L391
When the offset amount is larger than `buffer.len()`, it will only offset to the end of buffer.

I haven't found the code which can reproduce stably. I will try to fix it these days.

### PR DESCRIPTION
**Pull request by silver-ymz**
Close #80 

Update:
- Fix the incorrect behavior about `AsyncSeek` in `file::TokioCompatFile`
- leave error of exceeding buffer len in `consume` to handle by `BytesMut`

About the bug of `AsyncSeek`, I find a simpler solution. Since we won't use the buffer after seeking, we can just clear the buffer like `new_offset < prev_offset` situation.

### CODE REVIEW

File: src/file/tokio_compat_file.rs [hunk 1]
```diff
@@ -351,7 +351,11 @@ impl AsyncSeek for TokioCompatFile {
             if new_offset < prev_offset {
                 this.buffer.clear();
             } else if let Ok(offset) = (new_offset - prev_offset).try_into() {
-                self.consume(offset);
+                if offset > this.buffer.len() {
+                    this.buffer.clear();
+                } else {
+                    self.consume(offset);
+                }
```
Comment (NobodyXu) [inline src/file/tokio_compat_file.rs:358]:
```suggestion
                if offset > this.buffer.len() {
                    this.buffer.clear();
                } else {
                    this.buffer.advance(offset);
                }
                this.inner.offset += offset.try_into().unwrap();
```

**Review by NobodyXu — CHANGES_REQUESTED** [review]

File: src/file/tokio_compat_file.rs (hunk 1 above)
Comment (silver-ymz) [reply src/file/tokio_compat_file.rs:358]: We have increased the offset in https://github.com/openssh-rust/openssh-sftp-client/blob/ec5789501971ed6a5bd8382c2d02d185a21f9bb0/src/file/tokio_compat_file.rs#L343

This will increase the offset twice.

Comment (NobodyXu) [reply src/file/tokio_compat_file.rs]: Aha right.

But note that `<TokioCompatFile as AsyncBufRead::consume` also increases the offset.

I've updated my suggestion to not increase the offset.

Comment (NobodyXu) [reply src/file/tokio_compat_file.rs]: @silver-ymz I think we also need to fix `<File as AsyncBufRead>::consume` and `File as AsyncSeek`.

**Review by NobodyXu — CHANGES_REQUESTED** [review]

**Review by NobodyXu — APPROVED** [review]
