### PR TITLE
Fix panic when flush_interval is set to 0

### LINKED ISSUE #135: flush_interval set to 0 panics
https://docs.rs/openssh-sftp-client/latest/openssh_sftp_client/struct.SftpOptions.html#method.flush_interval

According to documentation:

> If flush_interval is set to 0, then every packet is flushed immediately.

But in reality it will attempt to set up periodic timer with duration zero:
https://github.com/openssh-rust/openssh-sftp-client/blob/main/src/tasks.rs#L68

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #135

### CODE REVIEW

File: src/tasks.rs [hunk 1]
```diff
@@ -65,8 +65,13 @@ pub(super) fn create_flush_task<W: AsyncWrite + Send + 'static>(
         write_end_buffer_size: NonZeroUsize,
         flush_interval: Duration,
     ) -> Result<(), Error> {
-        let mut interval = time::interval(flush_interval);
-        interval.set_missed_tick_behavior(time::MissedTickBehavior::Delay);
+        let mut interval = if flush_interval.is_zero() {
```
Comment (NobodyXu) [inline src/tasks.rs:68]:
```suggestion
        let mut interval = if !flush_interval.is_zero() {
```
