### PR TITLE
fix: hang with buffered I/O

### LINKED ISSUE #154: Hangs when used with tokio::io::stdin/stdout
Code is basically:

```rust
    let sftp = Sftp::new(tokio::io::stdout(), tokio::io::stdin(), SftpOptions::new()).await?;
    let dir = sftp.fs().open_dir(..).await?;
    let dir = dir.read_dir();
    // iterate over dir
```

Then run with:

```
dpipe ./target/debug/sftp-test = /path/to/sftp-server
```

And it hangs. apparent the hello was never written to stdout.

If I use pipe::Receiver/Sender instead it works.

### PR DESCRIPTION
**Pull request by silver-ymz**
Fix #154

`tokio::io::stdout()` wraps `std::io::Stdout`, which internally is a `LineWriter<StdoutRaw>`. Per the `AsyncWrite` contract, `poll_write` is allowed to buffer data without delivering it to the peer — only `poll_flush` guarantees delivery. `LineWriter` specifically only auto-flushes when it encounters a '\n'. Since SFTP is a binary protocol, its packets never contain '\n'.                                                                                      

The internal flush helper in `src/tasks.rs` called `write_all_bytes` to push the SSH_FXP_INIT "hello" packet into the writer, but never called `writer.flush()` afterward. With a buffered writer the packet stayed trapped in the internal buffer, the sftp-server never received it, never sent SSH_FXP_VERSION in reply, and `Sftp::new` blocked forever waiting for that reply. 

## Performance
For unbuffered writers (pipes, sockets, etc.) `poll_flush` is a no-op, so there is no overhead for the common case.

### CODE REVIEW

**Comment by silver-ymz** [comment]
cc @yshui, this fix seems to resolve your problem.

**Review by NobodyXu — APPROVED** [review]
Thank you for the quick PR!

It makes perfect sense, I forgot that the writer needs a flush (because I was dealing with i/o object with no buffering)

File: tests/buffered_writer.rs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+/// `poll_flush` is the only way to push it to the peer.
+use std::time::Duration;
+
+use openssh_sftp_client::{Sftp, SftpOptions};
+use sftp_test_common::launch_sftp;
+
+#[tokio::test]
+async fn sftp_new_works_with_buf_writer() {
+    let (mut child, stdin, stdout) = launch_sftp().await;
+    let buffered_stdin = tokio::io::BufWriter::new(stdin);
```
Comment (NobodyXu) [inline tests/buffered_writer.rs]: I think a better way to test this is to have a dedicated wrapper of writer, which indefinitely buffer data until an explicit `flush`, and we can also have that wrapper records whether a flush has happened through an `Arc<AtomicBool>`

**Review by NobodyXu — CHANGES_REQUESTED** [review]

File: tests/buffered_writer.rs (hunk 1 above)
Comment (silver-ymz) [reply tests/buffered_writer.rs]: updated

**Review by NobodyXu — APPROVED** [review]
Thanks LGTM

**Comment by yshui** [comment]
@silver-ymz thanks for fixing this so quickly!
